language: groovy
jdk:
  - oraclejdk8

services:
  - postgresql

postgres:
  adapter: postgresql
  database: blog
  username: postgres
before_script:
  - "psql -c 'create database blog;' -U postgres"

addons:
  apt:
    packages:
      - oracle-java8-installer
  postgresql: "9.4"

script:
  - ./gradlew check