hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: 'none'
            url: 'jdbc:postgresql://127.0.0.1:5432/blog'
            driverClassName: 'org.postgresql.Driver'
            dialect: 'org.hibernate.dialect.PostgreSQLDialect'
            username: 'blog'
            password: 'blog'
            logSql: true
    test:
        dataSource:
            dbCreate: create-drop
            url: 'jdbc:postgresql://127.0.0.1:5432/blog'
            driverClassName: 'org.postgresql.Driver'
            dialect: 'org.hibernate.dialect.PostgreSQLDialect'
            username: 'blog'
            password: 'blog'
            logSql: true
    production:
        dataSource:
            dbCreate: 'none'
            url: 'jdbc:postgresql://127.0.0.1:5432/blog'
            driverClassName: 'org.postgresql.Driver'
            dialect: 'org.hibernate.dialect.PostgreSQLDialect'
            username: 'blog'
            password: 'blog'
            logSql: false
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    profile: web
    codegen:
        defaultPackage: 'me.w2x.blog'
    spring:
        transactionManagement:
            proxies: false
    project:
        groupId: 'me.w2x.blog'
    app:
        context: "${(Environment.current == Environment.DEVELOPMENT ? 'gblog' : '/')}"
    exceptionresolver:
        params:
            exclude:
                - 'password'
    gorm:
        failOnError: true
    plugin:
          databasemigration:
              updateOnStart: true
              changelogLocation: 'grails-app/migrations'
              updateOnStartFileNames:
                  - 'changelog.groovy'
              dropOnStart: true
          springsecurity:
              auth:
                  loginFormUrl: '/admin/login/auth'
                  ajaxLoginFormUrl: '/admin/login/auth?ajax=true'
              apf:
                  filterProcessesUrl: '/admin/login/authenticate'
                  usernameParameter: 'username'
                  passwordParameter: 'password'
              logout:
                  filterProcessesUrl: '/admin/login/logoff'
                  postOnly: false
              password:
                  algorithm: 'bcrypt'
                  bcrypt:
                      logrounds: 15
              failureHandler:
                  ajaxAuthFailUrl: '/admin/login/authfail?ajax=true'
              successHandler:
                  ajaxSuccessUrl: '/admin/login/authsuccess?ajax=true'
              rejectIfNoRule: true
              fii:
                  rejectPublicInvocations: false
              userLookup:
                  userDomainClassName: 'me.w2x.blog.domain.account.User'
                  authorityJoinClassName: 'me.w2x.blog.domain.account.UserRole'
              authority:
                  className: 'me.w2x.blog.domain.account.Role'
              securityConfigType: "InterceptUrlMap"
              interceptUrlMap:
                  - pattern: '/assets/**'
                    access:
                        - 'permitAll'
                  - pattern: '/static/**'
                    access:
                        - 'permitAll'
                  - pattern: '/**/js/**'
                    access:
                        - 'permitAll'
                  - pattern: '/**/css/**'
                    access:
                        - 'permitAll'
                  - pattern: '/**/images/**'
                    access:
                        - 'permitAll'
                  - pattern: '/**/favicon.ico'
                    access:
                        - 'permitAll'
                  - pattern: '/admin/login/**'
                    access:
                        - 'permitAll'
                  - pattern: '/admin/**'
                    access:
                        - 'ROLE_ADMIN'
                  - pattern: '/**'
                    access:
                        - 'permitAll'
              filterChain:
                  chainMap:
                      - pattern: '/admin/**'
                        filters: 'JOINED_FILTERS'
                      - pattern: '/**'
                        filters: 'none'
              providerNames:
                  - 'rememberMeAuthenticationProvider'
                  - 'anonymousAuthenticationProvider'
                  - 'daoAuthenticationProvider'
              rememberMe:
                  alwaysRemember: false
                  persistent: true
                  persistentToken:
                      domainClassName: 'me.w2x.blog.domain.Session'

endpoints:
    jmx:
        unique-names: true

my:
    project:
        name: 'w2x'
        domain: 'w2x.me'


sequence:
    ShortenUrl:
      format: "%d"
    flushInterval: 30
